### PR TITLE
Image standardization, cleanup; adding 6.10.3

### PR DESCRIPTION
**Pull request by nickwalkmsft**
- General Dockerfile cleanup and standardization
- Moved proprietary server-side startup command generation logic to
generateStrtupCommand.js, run on container startup.
- Same for env vars (PM2HOME)
- Standardizing on port 8080 as default; correctly handling customer
setting of PORT appsetting
- Taking dependency on HTTP_LOGGING_ENABLED, which will now be set
for all containers (built in and custom)
- Default site is now a static express site hosted out of
/home/site/wwwroot, in line with standard

### CODE REVIEW

**Comment by nickwalkmsft** [comment]
Merging immediately. Sending to you guys as FYI if you want to have a look.

**Comment by lostintangent** [comment]
@nickwalkmsft Awesome! This change should enable us to enhance the core containers to detect startup scripts via package.json right? 

https://docs.npmjs.com/cli/start

**Comment by nickwalkmsft** [comment]
I believe that was always available, simply by putting "npm start" in the app startup command - the logic you see in generateStartupCommand.js is roughly what we've always had, it's just visible now. We have some work to do regarding the portal UX and what sane values are for "app startup command"/"startup file".

You can see the startup logic in generateStartupCommand.js, but just to sum it up here:

1. If your appCommandLine is two or more tokens, we run it directly, so you can do stuff like "npm start" or "node myapp.js myarg1 myarg2".
2. If your appCommandLine is a single token, we assume you're supplying a "startup file" script and we try to execute it with PM2 for robustness.
3. If your appCommandLine is empty, we hunt for a few conventional app names in wwwroot. We'll run one if we find it;  if we don't, we run the static page to show the preinstalled "Welcome to App Service" page.

We're trying to maintain a balance between "easy to get started" and "too much magic." Adding a check for a scripts.start in package.json might make a good addition to #3.

Please note that these images are pre-production - they are still subject to some review and testing, and they haven't yet been deployed.

**Comment by lostintangent** [comment]
Apologies, I was referring to an addition to #3. The auto-detection of a start script in package.json is already pretty well established in other products, so it would be a nice behavior to allow existing apps to be deployed, without needing to explicitly set the app command line flag.

**Comment by nickwalkmsft** [comment]
Yep, that's a good point, and a good idea. At that point we're looking around for unspecified files to run, we might as well check for a start script first. I should be able to get this in in a day or so. Thanks!

**Comment by lostintangent** [comment]
@nickwalkmsft Awesome! Thanks so much

**Comment by fiveisprime** [comment]
🎉 👍 

This is fantastic!

**Pull request merged**
